updated landing and partial for inner
aquasecurity/avd-generator pull request #28
Opened 2021-07-12 07:42 UTC by webuimaker

Updated landing page and inner page partial

2021-07-12 23:53 UTC, simar7 commented
@webuimaker Is this ready for review? If it's not, please mark it as a "Draft" until then. https://github.blog/2019-02-14-introducing-draft-pull-requests/

2021-07-13 07:30 UTC, webuimaker commented
> @webuimaker Is this ready for review? If it's not, please mark it as a "Draft" until then. https://github.blog/2019-02-14-introducing-draft-pull-requests/

Landing page done and inner page in progress but I will keep this is in next time

2021-07-14 08:34 UTC, webuimaker commented
Please merge and check I have update inner page too.

2021-07-14 18:27 UTC, simar7 commented on .vscode/configurationCache.log
> +{"buildTargets":[],"launchTargets":[],"customConfigurationProvider":{"workspaceBrowse":{"browsePath":[]},"fileIndex":[]}}
Remove

2021-07-14 18:27 UTC, simar7 commented on .vscode/dryrun.log
> +
Remove

2021-07-14 18:27 UTC, simar7 commented on .vscode/settings.json
> +}
Remove

2021-07-14 18:29 UTC, simar7 commented on content/cspm/_index.md
> +- TLS Version Check
What are these?

2021-07-14 18:33 UTC, simar7 commented on content/cspm/aws/acm/acm-certificate-validation.md
> +
What's this for?

2021-07-14 18:34 UTC, simar7 commented on themes/aquablank/layouts/partials/featured.html
> +</div><!-- projects_wrap -->
These are hardcoded, how do we plan to generate this automatically?

2021-07-14 18:36 UTC, simar7 commented on themes/aquablank/layouts/partials/home.html
> +
The links don't work here. For example /appshield returns back to the home page.

2021-07-14 18:38 UTC, simar7 commented on themes/aquablank/layouts/partials/list_cloudsploit.html
> +                </div>
Also don't work. They are all pointing to /cspm. What were you trying to implement here?

2021-07-14 18:39 UTC, simar7 commented on themes/aquablank/layouts/partials/startnow.html
> +                </div>
Is this the right size? Looks quite off for me: 
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/1254783/125675075-03952b3d-a409-4bcb-809a-1184b1e62ef2.png">

2021-07-14 18:42 UTC, simar7 commented on content/cspm/aws/acm/acm-certificate-validation.md
> +| Issue ID | AZU001 |
There isn't any ID associated here. Were you trying to use this as a key for something? If so use The actual Plugin Title has it is unique.

2021-07-14 18:43 UTC, simar7 commented on content/cspm/aws/acm/acm-certificate-validation.md
> +{{< codetab >}}
What happens if a policy doesn't have both steps? Do we still show the tabs?

2021-07-14 18:45 UTC, simar7 commented on themes/aquablank/layouts/partials/page_cloudsploit.html
> +                    </div>
We need to pull this from the page not hardcode as different things will have different severity classification.

2021-07-14 18:47 UTC, simar7 requested changes
Left some comments. For the UI specific pages, could you also attach a screenshot to show the changes with the PR comments going forward?

2021-09-14 08:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/avd-generator?pullRequest=28) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/avd-generator?pullRequest=28) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/avd-generator?pullRequest=28) it.</sub>

2022-01-18 23:50 UTC, closed without merging